<h1>Calculator V. 9000</h1>

<form action="includes/calc.inc.php" method="post">
    <p>Calculationing is <strong>Fun</strong>!</p>
    <input type="number" name="num1" id="num1" placeholder="First number...">
    <select name="oper" id="oper">
        <option value="add" selected>Add</option>
        <option value="sub">Subtract</option>
        <option value="div">Divide</option>
        <option value="mul">Multiply</option>
    </select>
    <input type="number" name="num2" id="num2" placeholder="Second number...">
    <input type="submit" value="Calculate!">

</form>