<div class="container">
  <input type="checkbox" id="flip" />
  <div class="cover">
    <div class="front">
      <img src="assets/img/frontImg.jpg" alt="" />
      <div class="text">
        <span class="text-1">Every new friend is a <br />
          new adventure</span>
        <span class="text-2">Let's get connected</span>
      </div>
    </div>
    <div class="back">
      <img class="backImg" src="assets/img/backImg.jpg" alt="" />
      <div class="text">
        <span class="text-1">Complete miles of journey <br />
          with one step</span>
        <span class="text-2">Let's get started</span>
      </div>
    </div>
  </div>
  <div class="forms">
    <div class="form-content">
      <div class="login-form">
        <div class="title">Login</div>
        <form action="includes/login.inc.php" method="post" name="login" id="login">
          <div class="input-boxes">
            <div class="input-box">
              <i class="fas fa-envelope"></i>
              <input type="email" placeholder="Enter your email" name="email" required />
            </div>
            <div class="input-box">
              <i class="fas fa-lock"></i>
              <input
                type="password"
                placeholder="Enter your password"
                name="passwd"
                required />
            </div>
            <div class="text"><a href="#">Forgot password?</a></div>
            <div class="button input-box">
              <input type="submit" value="Submit" />
            </div>
            <div class="text sign-up-text">
              Don't have an account? <label for="flip">Sign up now</label>
            </div>
          </div>
        </form>
      </div>
      <div class="signup-form">
        <div class="title">Sign Up</div>
        <form action="includes/signup.inc.php" method="post" name="signup" id="signup">
          <div class="input-boxes">
            <div class="input-box">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Enter your name" name="uid" />
            </div>
            <div class="input-box">
              <i class="fas fa-envelope"></i>
              <input type="email" placeholder="Enter your email" name="email" required />
            </div>
            <div class="input-box">
              <i class="fas fa-lock"></i>
              <input
                type="password"
                placeholder="Enter your password"
                name="passwd"
                required />
            </div>
            <div class="input-box">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Re-enter password" name="reppasswd" required />
            </div>
            <div class="button input-box">
              <input type="submit" name="submit" value="Sumbit" />
            </div>
            <div class="text sign-up-text">
              Already have an account? <label for="flip">Login now</label>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>