<header>
    <nav>
        <div class="nav-section-left">
            <h1 class="page-title">DOUGLAS FIRM Inc.</h1>
            <ul class="nav-links">
                <li>Home</li>
                <li>Products</li>
                <li>Current Sales</li>
                <li>Member</li>
            </ul>
        </div>
        <ul class="nav-section-right">
            <li class="nav-signup nav-button">Sign Up</li>
            <div class="vertical-div"></div>
            <li type="button" class="nav-login nav-button">Login</li>
        </ul>

    </nav>
</header>
<section class="banner">
    <img src="../assets/img/banner-background.jpeg" alt="main page banner showing petty image">
</section>